### ISSUE TITLE
Add an about page

### ISSUE THREAD

**Issue by reyesjl** [reyesjl/firstfiverugby#16]
Hey Joe put your stuff in here that you want please :)

**Comment by jritter64** [comment]
Tim Brown has played, coached and served as an administrator for rugby clubs both domestically and internationally for the last 30 years. He has worked with multiple unions, many universities, Old Glory DC, the Leicester Tigers and others on player recruitment, camps and tours. 

First 5 will be the premier portal to make it easy for players, coaches and fans to get the resources they want and need to grow the game 

————-
Joseph Ritter graduated from the University of Mary Washington and still plays competitively today. Ritter works as a Project Manager for his family’s company, Cedar Shakes and Shingles. 

First Five Rugby will promote grass roots rugby by providing accessibility to knowledge, equipment, and education.
